"""Initial migration

Revision ID: 05d83b99744f
Revises: 
Create Date: 2024-09-26 13:47:42.599491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05d83b99744f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.add_column('activity_logs', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'activity_logs', 'projects', ['project_id'], ['id'])
    op.add_column('training_data', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('training_data_user_id_fkey', 'training_data', type_='foreignkey')
    op.create_foreign_key(None, 'training_data', 'projects', ['project_id'], ['id'])
    op.drop_column('training_data', 'user_id')
    op.drop_column('training_data', 'updated_at')
    op.drop_column('training_data', 'bot_id')
    op.drop_column('training_data', 'data')
    op.drop_column('training_data', 'created_at')
    op.drop_column('training_data', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_data', sa.Column('status', postgresql.ENUM('TRAINING', 'COMPLETED', 'FAILED', name='modelstatus'), autoincrement=False, nullable=True))
    op.add_column('training_data', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('training_data', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('training_data', sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('training_data', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('training_data', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'training_data', type_='foreignkey')
    op.create_foreign_key('training_data_user_id_fkey', 'training_data', 'users', ['user_id'], ['id'])
    op.drop_column('training_data', 'project_id')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'project_id')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
