"""Update TrainingData relationships

Revision ID: 75e70c80ca2f
Revises: 05d83b99744f
Create Date: 2024-09-26 13:49:16.438868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e70c80ca2f'
down_revision: Union[str, None] = '05d83b99744f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_data', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('training_data', sa.Column('data', sa.JSON(), nullable=False))
    op.add_column('training_data', sa.Column('status', sa.Enum('TRAINING', 'COMPLETED', 'FAILED', name='modelstatus'), nullable=True))
    op.add_column('training_data', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('training_data', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('training_data', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'training_data', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_data', type_='foreignkey')
    op.drop_column('training_data', 'updated_at')
    op.drop_column('training_data', 'created_at')
    op.drop_column('training_data', 'file_url')
    op.drop_column('training_data', 'status')
    op.drop_column('training_data', 'data')
    op.drop_column('training_data', 'user_id')
    # ### end Alembic commands ###
