"""Update Chat model to remove user relationship

Revision ID: a37674c7fe51
Revises: 75e70c80ca2f
Create Date: 2024-09-26 13:52:09.175176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37674c7fe51'
down_revision: Union[str, None] = '75e70c80ca2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('sender_name', sa.String(length=100), nullable=False))
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    op.drop_column('chats', 'sender_name')
    # ### end Alembic commands ###
